export const STORAGE_KEY = "acad_marks_v1";

export const GRADE_RULES = [
  { min: 90, grade: "O",  label: "Outstanding",  gpa: 10 },
  { min: 80, grade: "A+", label: "Excellent",     gpa: 9  },
  { min: 70, grade: "A",  label: "Very Good",     gpa: 8  },
  { min: 60, grade: "B+", label: "Good",          gpa: 7  },
  { min: 50, grade: "B",  label: "Above Average", gpa: 6  },
  { min: 40, grade: "C",  label: "Average",       gpa: 5  },
  { min: 0,  grade: "F",  label: "Fail",          gpa: 0  },
];

export const COLORS = [
  "#6C63FF", "#FF6584", "#43C6AC", "#F7971E",
  "#56CCF2", "#BB6BD9", "#2D9CDB", "#EB5757"
];

export const styles = {
  app:        { display: "flex", minHeight: "100vh", fontFamily: "'Nunito', 'Segoe UI', sans-serif", background: "#F8F7FF" },
  sidebar:    { width: 220, background: "#1C1B3A", display: "flex", flexDirection: "column", padding: "24px 0", flexShrink: 0 },
  brand:      { display: "flex", alignItems: "center", gap: 10, padding: "0 20px 24px", borderBottom: "1px solid rgba(255,255,255,0.08)" },
  brandIcon:  { fontSize: 28 },
  brandTitle: { color: "#fff", fontWeight: 800, fontSize: 16, lineHeight: 1.2 },
  brandSub:   { color: "#9CA3AF", fontSize: 11 },
  nav:        { padding: "16px 12px", flex: 1 },
  navBtn:     { display: "flex", alignItems: "center", gap: 10, width: "100%", padding: "10px 12px", marginBottom: 4, background: "none", border: "none", cursor: "pointer", borderRadius: 8, color: "#9CA3AF", fontSize: 14, fontWeight: 600, transition: "all .15s", textAlign: "left" },
  navActive:  { background: "rgba(108,99,255,0.2)", color: "#fff" },
  navIcon:    { fontSize: 18, width: 22, textAlign: "center" },
  sideStats:  { padding: "16px", borderTop: "1px solid rgba(255,255,255,0.08)", display: "flex", gap: 8, flexWrap: "wrap" },
  statPill:   { background: "rgba(255,255,255,0.08)", color: "#C4B5FD", fontSize: 12, padding: "4px 10px", borderRadius: 12 },
  main:       { flex: 1, display: "flex", flexDirection: "column", minWidth: 0 },
  header:     { background: "#fff", borderBottom: "1px solid #E5E7EB", padding: "16px 28px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  pageTitle:  { margin: 0, fontSize: 22, fontWeight: 800, color: "#1C1B3A" },
  headerRight:{ display: "flex", alignItems: "center", gap: 12 },
  badge:      { background: "#EDE9FE", color: "#6C63FF", fontSize: 12, fontWeight: 700, padding: "4px 12px", borderRadius: 20 },
  content:    { padding: 24, flex: 1, overflowY: "auto" },
  kpiGrid:    { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16, marginBottom: 20 },
  kpiCard:    { background: "#fff", borderRadius: 12, padding: "20px 16px", textAlign: "center", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" },
  kpiIcon:    { fontSize: 28, marginBottom: 8 },
  kpiValue:   { fontSize: 32, fontWeight: 800, lineHeight: 1 },
  kpiLabel:   { color: "#6B7280", fontSize: 12, marginTop: 4 },
  chartsRow:  { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 20 },
  chartCard:  { background: "#fff", borderRadius: 12, padding: 20, boxShadow: "0 1px 4px rgba(0,0,0,0.06)" },
  chartTitle: { fontWeight: 800, fontSize: 15, color: "#1C1B3A", marginBottom: 12 },
  topRow:     { display: "flex", alignItems: "center", gap: 10, padding: "8px 0", borderBottom: "1px solid #F3F4F6" },
  rank:       { width: 24, height: 24, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 800 },
  twoCol:     { display: "grid", gridTemplateColumns: "320px 1fr", gap: 20 },
  formCard:   { background: "#fff", borderRadius: 12, padding: 24, boxShadow: "0 1px 4px rgba(0,0,0,0.06)", height: "fit-content" },
  tableCard:  { background: "#fff", borderRadius: 12, padding: 20, boxShadow: "0 1px 4px rgba(0,0,0,0.06)" },
  cardTitle:  { fontWeight: 800, fontSize: 16, color: "#1C1B3A", marginBottom: 16 },
  label:      { display: "block", fontSize: 13, fontWeight: 700, color: "#374151", marginBottom: 12 },
  input:      { display: "block", width: "100%", marginTop: 4, padding: "9px 12px", border: "1.5px solid #E5E7EB", borderRadius: 8, fontSize: 14, boxSizing: "border-box", outline: "none", fontFamily: "inherit" },
  btn:        { display: "block", width: "100%", padding: "11px", background: "#6C63FF", color: "#fff", border: "none", borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: "pointer", marginTop: 16 },
  iconBtn:    { background: "none", border: "none", cursor: "pointer", fontSize: 16, padding: "2px 6px" },
  table:      { width: "100%", borderCollapse: "collapse", fontSize: 14 },
  th:         { background: "#F3F4F6", padding: "10px 12px", textAlign: "left", fontWeight: 700, fontSize: 12, color: "#6B7280", borderBottom: "2px solid #E5E7EB" },
  td:         { padding: "10px 12px", borderBottom: "1px solid #F3F4F6", color: "#374151" },
  tr:         { transition: "background .1s" },
  gradeBadge: { borderRadius: 8, padding: "10px 14px", fontWeight: 600, fontSize: 14, marginBottom: 8 },
  gradeChip:  { display: "inline-block", padding: "2px 10px", borderRadius: 12, fontWeight: 800, fontSize: 13 },
  infoNote:   { background: "#EEF2FF", color: "#4F46E5", fontSize: 13, padding: "8px 12px", borderRadius: 8, marginBottom: 8 },
  infoBox:    { background: "#F0FDF4", border: "1px solid #BBF7D0", borderRadius: 12, padding: 20, marginBottom: 20, fontSize: 14, lineHeight: 1.7 },
  dropZone:   { border: "2px dashed #C4B5FD", borderRadius: 16, padding: "56px 20px", textAlign: "center", cursor: "pointer", marginBottom: 20, transition: "all .2s", background: "#FAFAFF" },
  dropActive: { borderColor: "#6C63FF", background: "#EDE9FE" },
  successNote:{ background: "#DCFCE7", color: "#15803d", padding: "10px 16px", borderRadius: 8, marginBottom: 16, fontWeight: 600 },
  toast:      { position: "fixed", bottom: 24, right: 24, color: "#fff", padding: "12px 20px", borderRadius: 10, fontWeight: 700, fontSize: 14, zIndex: 999, boxShadow: "0 4px 20px rgba(0,0,0,0.15)" },
};
